name: avocado_common
description: The avocado common DL/BL package.
version: 1.0.2
# homepage: https://www.example.com
# author: guy.p <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  resource: ^2.1.5 
  rxdart: ^0.20.0
  json_annotation: ^2.0.0
  built_redux:
    git: https://github.com/guypeled76/built_redux
  built_redux_saga:
    git: https://github.com/guypeled76/built_redux_saga
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.3.0
  json_serializable: ^2.0.1
  test: ^1.0.0
