name: avocado_common
description: The avocado common DL/BL package.
version: 1.0.2
# homepage: https://www.example.com
# author: guy.p <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  built_value: ^6.2.0
  built_collection: ^4.1.0
  resource: ^2.1.5 
  rxdart: ^0.20.0
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  built_value_generator: ^6.2.0
