name: avocado_common
description: The avocado common DL/BL package.
version: 1.0.2
# homepage: https://www.example.com
# author: guy.p <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  resource: ^2.1.6
  rxdart: ^0.22.0
  json_annotation: ^2.4.0
  built_redux: ^7.5.4
  built_redux_saga: ^1.0.11

dev_dependencies:
  build_runner: ^1.6.1
  built_value_generator: ^6.6.0
  json_serializable: ^3.0.0
  test: ^1.6.4
