runtime: go112

env_variables:
  PORT: "8080"
  SCHEMA: "http"
  CLOUDSQL_CONNECTION_NAME: "avocado-services:europe-west2:avocado-database"
  CLOUDSQL_USER: "avocado"
  CLOUDSQL_PASSWORD: "Newron123"
  GOOGLE_CLIENT_ID: "612947651641-gtqgvd2j7mi1gocvldohkob78oo83m1i.apps.googleusercontent.com"
  GOOGLE_SECRET: "KQrAojiEsRtdHA1vVRK8ZAC0"

