global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
targets:
  $default:
    builders:
      angular_components|scss_builder:
        enabled: True
      angular_gallery_section|angular_gallery_section:
        options:
          staticImageServer: "https://raw.githubusercontent.com"
      angular|angular:
        enabled: true
      build_web_compilers|dart2js_archive_extractor:
        release_options:
          filter_outputs: false
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          dart2js_args:
            - --fast-startup
            - --minify
            - --trust-primitives
            - --omit-implicit-checks
            - --dump-info