name: avocado_web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: guy.p <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_router: ^2.0.0-alpha+21
  avocado_common:
    path: ../avocado_common
  build_config: '>=0.2.6 <0.4.0'
  firebase: ^5.0.2

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1

