apiVersion: apps/v1
kind: Deployment
metadata:
  name: avocado-server
  labels:
    app: avocado-server
spec:
  selector:
    matchLabels:
      app: avocado-server
  template:
    metadata:
      labels:
        app: avocado-server
    spec:
      containers:
        - name: web
          image: eu.gcr.io/avocado-backend/avocado_server:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: 127.0.0.1:3306
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command: ["/cloud_sql_proxy",
                    "-instances=avocado-backend:europe-west2:avocado-database=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
